### ISSUE TITLE
shouldRecycle=false breaks UI when scrolling the elements fast.

### ISSUE THREAD

**Issue by ahamedalthaf** [html-next/vertical-collection#296]
'shouldRecycle: false' is breaking the UI when we try to scroll faster. This breaks the UI and completely block the user from doing any activity. 

Please find the error below in the browser console.

**Assertion Failed: value must non-negative**

**Comment by rwwagner90** [comment]
@ahamedalthaf can you try the latest version please?

**Comment by ahamedalthaf** [comment]
@rwwagner90 tried with latest version and still seeing the same issue.

**Comment by NullVoxPopuli** [comment]
I'm experiencing this on emberclear, too :(

**Comment by ahamedalthaf** [comment]
@rwwagner90 I have fixed this issue in the PR raised. Please check from your side.

**Comment by rwwagner90** [comment]
Thanks @ahamedalthaf!

**Comment by knownasilya** [comment]
Was seeing `nextSibling` of undefined in the glimmer vm with this flag as well.

**Comment by jbottigliero** [comment]
While the referenced PR has been merged for some time (looks like it would have landed in `3.0.0`), I'm encountering a similar error in newer versions.

I've tested in both `4.0.1` and `3.1.0`, both versions result in a similar error, the below report is from `4.0.1` (latest at time of writing):

```js
Uncaught Error: Assertion Failed: value must non-negative
    at Object.assert (index.js:181:1)
    at SkipList.set (-private.js:1486:1)
    at DynamicRadar._measure (-private.js:1762:1)
    at DynamicRadar._updateIndexes (-private.js:1656:1)
    at DynamicRadar.update (-private.js:782:1)
    at -private.js:769:1
    at Array.execJob (index.js:36:1)
    at Scheduler.flush (index.js:96:1)
    at index.js:82:1
````

I'll try and follow-up with more details as I begin to investigate...

**Comment by wozny1989** [comment]
Anyone got an idea how to fix this? We have the same reason as @NullVoxPopuli to use `shouldRecycle={{true}}`

**Comment by NullVoxPopuli** [comment]
since I posted my comment, I've found that using derived data _for everything_ solves most problems.

did-insert/did-update/will-destroy are problematic for more than just this scenario, but also outside of Ember. `useEffect` in React suffers from the same problem, as do other effect implementations in other frameworks, such as Preact, Solid, etc.

By using derived data, you appropriately get the correct behavior when you need it (when the root state changes, which is what happens during component re-use)
