### ISSUE TITLE
Uncaught: Changing a view's elementId after creation is not allowed

### ISSUE THREAD

**Issue by pzuraq** [html-next/vertical-collection#95]
Ember Version: 2.10.2
Vertical Collection Version: 58a7e4d0cf339469369a6ec35a0c39b3520e61ac

Getting an uncaught error being thrown during the scheduler's `run.end()`:

```
Changing a view's elementId after creation is not allowed

Error
    at Object.EmberError [as Error] (http://localhost:4200/assets/vendor.js:27636:14)
    at eval (eval at <anonymous> (http://localhost:4200/assets/vendor.js:52422:11), <anonymous>:1:17)
    at Class.<anonymous> (http://localhost:4200/assets/vendor.js:52422:11)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:27972:18)
    at notifyBeforeObservers (http://localhost:4200/assets/vendor.js:31918:25)
    at Object.propertyWillChange (http://localhost:4200/assets/vendor.js:31701:7)
    at Object.set (http://localhost:4200/assets/vendor.js:32141:34)
    at http://localhost:4200/assets/vendor.js:32976:33
    at Object.changeProperties (http://localhost:4200/assets/vendor.js:31901:16)
    at Object.setProperties (http://localhost:4200/assets/vendor.js:32969:32)
```

**Comment by alexander-alvarez** [comment]
So I bumped versions to `2.11.3`, `2.12.2`, and `2.13.2` and was getting the same error, so I think it's related to the configuration in offirgolan/ember-light-table@master...alexander-alvarez:perf-analysis exposing something that isn't playing nice.


the above stack trace stems from the radar's `scheduleUpdate`
```js
    _initializeEventHandlers: function _initializeEventHandlers() {
      var _this3 = this;

      this._scrollHandler = function (_ref2) {
        var top = _ref2.top;

        if (Math.abs(_this3._lastEarthquake - top) > _this3._radar._minHeight / 2) {
          _this3._radar.scheduleUpdate(); // here
          _this3._lastEarthquake = top;
        }
      };

```

**Comment by pzuraq** [comment]
So I took a look at the code this morning, it looks like this line is what's causing it: https://github.com/alexander-alvarez/ember-light-table/blob/perf-analysis/addon/templates/components/lt-body.hbs#L17

The issue is that we recycle these components, and Ember won't let you manually change the `elementId` of a component that has already been rendered. Is there a reason you need to have the `elementId` be the `rowId`?

**Comment by alexander-alvarez** [comment]
not sure -- @offirgolan would know better

**Comment by offirgolan** [comment]
@alexander-alvarez @pzuraq yeah I ran into the same issue when I was playing around with this as well. A simple workaround is to store the rowId as a `data` attribute instead 😄

**Comment by pzuraq** [comment]
Ok, going to close this issue because I don't think we can do anything about this without sacrificing performance.
